### ISSUE TITLE
LINQ extensions do not honor JSON naming policy

### ISSUE THREAD

**Issue by jmorrill** [coronabytes/dotnet-arangodb-extensions#3]
If you use a camel case json policy (or any other non default policy) on your documents, the query generated by the LINQ extensions do not generate correct queries.

For instance:

class Document
{
     public string Label{get;set;} = "value"
}

Serializes to:

{ label: "value" }

and a query like: ...Where(e.Label == "value") will generate a query for "Label", not "label".

**Comment by coronabytes** [comment]
Yup, unfortunatly the LINQ extensions is entirely "unsupported"  (Student thesis)
If u want it fixed anytime soon - you'd probably want give the "AsQueryable" an option and execute

```csharp
private static void FixCasing(Span<char> chars)
        {
            for (int i = 0; i < chars.Length; i++)
            {
                if (i == 1 && !char.IsUpper(chars[i]))
                {
                    break;
                }

                bool hasNext = (i + 1 < chars.Length);

                // Stop when next char is already lowercase.
                if (i > 0 && hasNext && !char.IsUpper(chars[i + 1]))
                {
                    // If the next char is a space, lowercase current char before exiting.
                    if (chars[i + 1] == ' ')
                    {
                        chars[i] = char.ToLowerInvariant(chars[i]);
                    }

                    break;
                }

                chars[i] = char.ToLowerInvariant(chars[i]);
            }
        }
```
on any name written.


OR actually name the c# propertys camelCase.... 
the translator just transofrm thr C# code as it sees it to AQL
there is no json serialization involved

**Comment by coronabytes** [comment]
now possible in core driver
