### ISSUE TITLE
Web UI to access management features

### ISSUE THREAD

**Issue by weedkiller** [coronabytes/dotnet-arangodb-extensions#5]
hi we need a management page for features

**Comment by coronabytes** [comment]
Had to read https://github.com/arangodb/arangodb/issues/13906 to even get a grasp of what you meant...

I'd say wrong scope and project.

What we do for export / import (tenant copy/move) however is to iterate over all collections and use Document.ExportAsync to JObject and stream that into a ZipArchive.

HotBackup is not intended for that.
