### ISSUE TITLE
Devextreme extensión filtering and sorting

### ISSUE THREAD

**Issue by Ghaby74** [coronabytes/dotnet-arangodb-extensions#6]
I'm testing Devextreme extension with a dxDataGrid and filtering and sorting operations only works with key field, not working with other fields

This is the dxDataGrid

@(Html.DevExtreme().DataGrid<SampleOrder>()
    .ShowBorders(true)
    .DataSource(d => d.Mvc().Controller("SampleData").LoadAction("Get").Key("_id"))
    .Columns(columns => {
        columns.Add().DataField("_key");
        columns.Add().DataField("name");
        columns.Add().DataField("population");
        columns.Add().DataField("isCapital");
    })
    .Paging(p => p.PageSize(10))
    .FilterRow(f => f.Visible(true))
    .HeaderFilter(f => f.Visible(true))
    .RemoteOperations(true)

This is my api

    [Route("api/[controller]")]
    public class SampleDataController : Controller {

        [HttpGet]
        public async Task<object> Get(DataSourceLoadOptions loadOptions) {

            // from connection string
            var arango = new ArangoContext("Server=http://localhost:8529;User=root;Password=12345678a.;");
            ArangoHandle db = new ArangoHandle("TEST");
            var arangoTransform = new ArangoTransform(loadOptions, Transform);
            if (!arangoTransform.Transform(out var error))
                return BadRequest(error);

            var data= await arangoTransform.ExecuteAsync<City>(arango, db, "germanCity");

            return data;
            //return DataSourceLoader.Load(SampleData.Orders, loadOptions);
        }

        private static readonly ArangoTransformSettings Transform = new ArangoTransformSettings
        {
            IteratorVar = "x",
            Key = "key",
            //Filter = "x.Active == true",
        };

        public class Geometry
        {
            public string type { get; set; }
            public List<double> coordinates { get; set; }
        }

        public class City
        {
            public string _key { get; set; }
            public string _id { get; set; }
            public string _rev { get; set; }
            public string name { get; set; }
            public int population { get; set; }
            public bool isCapital { get; set; }
            public Geometry geometry { get; set; }
        }
    }

this is my collection data

[{"_key":"Berlin","_id":"germanCity/Berlin","_rev":"_e_x6lZm---","name":"Berlin","population":3000000,"isCapital":true,"geometry":{"type":"Point","coordinates":[13.3833,52.5167]}},{"_key":"Hamburg","_id":"germanCity/Hamburg","_rev":"_e_x63Wi---","name":"Hamburg","population":1000000,"isCapital":false,"geometry":{"type":"Point","coordinates":[10.0014,53.5653]}},{"_key":"Cologne","_id":"germanCity/Cologne","_rev":"_e_x7HEi---","name":"Cologne","population":1000000,"isCapital":false,"geometry":{"type":"Point","coordinates":[6.9528,50.9364]}}]

**Comment by Ghaby74** [comment]
I've seen the problem. My properties are in lowercase and the code converts first character of properties name to upper with .FirstCharOfPropertiesToUpper()

**Comment by coronabytes** [comment]
Yes the driver is "optimized" for PascalCase Arango and camelCase JavaScript Model.
you can override this behavior with propertyname config
