### ISSUE TITLE
Devextreme extension Select options

### ISSUE THREAD

**Issue by Ghaby74** [coronabytes/dotnet-arangodb-extensions#7]
How can I use the select options? I always getting an error.

passing 

{
  "select": [
    "x.Nombre"
  ]
}

I get 

    "Message": "Unexpected character encountered while parsing value: x. Path '', line 0, position 0.",

If i try with {

  "select": [
    "Nombre"
  ]
}

I get 

    "Message": "Error parsing NaN value. Path '', line 1, position 1.",

**Comment by coronabytes** [comment]
what select options?
is this on the javascript side?

**Comment by Ghaby74** [comment]
Sorry, it seems to be a problem of Newtonsoft when parsing the request

**Comment by coronabytes** [comment]
yes, the selection is always 'developer' controlled.
honestly we're using devex for yearss and have never seen 'select' been send from our controls

**Comment by Ghaby74** [comment]
I always use 'select' option, overall with dxDatagrid, to bring only necesary fields, and not all fields, to reduce de amount of data with unnecesary fields. Tanks.

**Comment by coronabytes** [comment]
ok, if you really wanted something like that you could build the projection out of the select json easily.
